apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: multicluster-role-assignment
    app.kubernetes.io/managed-by: multiclusterhub-operator
    velero.io/exclude-from-backup: "true"
  name: multicluster-role-assignment-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-role-assignment-manager-role
subjects:
  - kind: ServiceAccount
    name: multicluster-role-assignment-controller
    namespace: {{ .Values.global.namespace }}
