apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: multicluster-role-assignment
    app.kubernetes.io/managed-by: multiclusterhub-operator
    velero.io/exclude-from-backup: "true"
  name: multicluster-role-assignment-controller
  namespace: {{ .Values.global.namespace }}
