apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: multicluster-role-assignment
    app.kubernetes.io/managed-by: multiclusterhub-operator
    velero.io/exclude-from-backup: "true"
  name: multicluster-role-assignment-leader-election-rolebinding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multicluster-role-assignment-leader-election-role
subjects:
  - kind: ServiceAccount
    name: multicluster-role-assignment-controller
    namespace: {{ .Values.global.namespace }}
